import { env } from "@/lib/config/env";

export interface SpellCheckResult {
  original: string;
  corrected: string;
  changes: Array<{ word: string; suggestion: string; position: { start: number; end: number } }>;
}

export interface AICleanupResult {
  original: string;
  cleaned: string;
  provider: "gemini" | "openai";
}

export interface SummarizeResult {
  summary: string;
  provider: "gemini" | "openai";
}

export async function aiCleanup(text: string): Promise<AICleanupResult> {
  try {
    const result = await cleanupWithGemini(text);
    return { original: text, cleaned: result, provider: "gemini" };
  } catch {
    const result = await cleanupWithOpenAI(text);
    return { original: text, cleaned: result, provider: "openai" };
  }
}

export async function summarize(text: string, title?: string): Promise<SummarizeResult> {
  const prompt = `You are a content summarizer. Given a YouTube video transcript, write a clear and concise summary with: 1) A one-sentence overview, 2) 3-5 key points as bullet points, 3) Main takeaway. Be brief and informative.\n\nVideo: "${title || "YouTube Video"}"\n\nTranscript:\n${text}`;

  try {
    const result = await geminiGenerate(prompt);
    return { summary: result, provider: "gemini" };
  } catch {
    const result = await openaiGenerate(prompt);
    return { summary: result, provider: "openai" };
  }
}

const CLEANUP_PROMPT = `You are a transcript cleanup assistant. Your job is to take a raw YouTube transcript and make it readable while keeping EVERY piece of content intact.

RULES:
1. PRESERVE ALL CONTENT. Do NOT shorten, summarize, or skip any part of the transcript. The output must cover the ENTIRE input from start to finish.
2. Fix obvious spelling and grammar mistakes. Many YouTube transcripts are auto-generated by speech-to-text AI, so expect wrong words, misspellings, missing punctuation, and broken sentences.
3. Add proper punctuation (periods, commas, question marks) where missing.
4. Fix capitalization (start of sentences, proper nouns, acronyms).
5. Merge sentence fragments that were split across caption segments into complete sentences.
6. Organize into natural paragraphs (group related sentences together, add paragraph breaks at topic changes).
7. Keep the speaker's original words and phrasing. Do NOT rewrite sentences in your own words. If they said "gonna", keep "gonna". If they said "y'all", keep "y'all".
8. For filler words (um, uh, like, you know): only remove them when they add zero meaning. If "like" is used as a comparison or "you know" is part of a rhetorical question, keep it.
9. If a word looks wrong but you're unsure what the speaker actually said, leave it as-is rather than guessing.
10. Do NOT add any commentary, headers, labels, or explanation. Return ONLY the cleaned transcript text.

TRANSCRIPT:
`;

async function cleanupWithGemini(text: string): Promise<string> {
  return geminiGenerate(CLEANUP_PROMPT + text);
}

async function cleanupWithOpenAI(text: string): Promise<string> {
  return openaiGenerate(CLEANUP_PROMPT + text);
}

async function geminiGenerate(prompt: string): Promise<string> {
  const url =
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" +
    env.GEMINI_API_KEY;
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        maxOutputTokens: 8192,
      },
    }),
  });
  if (!response.ok) throw new Error("Gemini failed");
  const data = await response.json();
  return data.candidates?.[0]?.content?.parts?.[0]?.text || "";
}

async function openaiGenerate(prompt: string): Promise<string> {
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: "Bearer " + env.OPENAI_API_KEY,
    },
    body: JSON.stringify({
      model: "gpt-3.5-turbo",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 4096,
    }),
  });
  if (!response.ok) throw new Error("OpenAI failed");
  const data = await response.json();
  return data.choices?.[0]?.message?.content || "";
}
